<?=$this->doctype() ?>
<html>
    <head>
        <?= $this->headScript()->appendFile('/js/jquery-1.9.1.min.js') ?>
    </head>
    <style>
        body {
            margin:0; 
            padding:0; 
            text-align:center; 
            background:#eee; 
            box-shadow:inset 0 0 10em #aaa; 
            min-width:100%; 
            min-height:100%;
            position:absolute;
            font-family:Arial, Helvetica, sans-serif;
            }
         #readContainer {margin:3em 1em 1em; min-width:35em; display:inline-block; position:relative;}
         #readContainer #message {font-size:1.5em; color:#922}
         #readContainer table {text-align:left; font-size:1.1em; width:100%}
         #readContainer table th {
             text-align:right; 
             color:#777; 
             font-size:.8em; 
             font-weight:normal; 
             vertical-align:top;
             padding:.5em 1em;
             }
         #readContainer textarea {
            width:98%; 
            padding:1%; 
            font-size:1.3em;
            border:1px solid #aaa;
            background:rgba(255,255,255,.6);
            box-shadow:inset 0 0 .1em #999;
            border-radius:.1em;
            margin-bottom:1em;
            min-height:10em;
            height:15em;
            min-width:30em;
            }
            
         #readContainer .email {color:#569; margin-left:.5em}  
    </style>
    <body>
        <div id="readContainer">
            <div id="message"><?=$this->message?></div>
            <? if ($this->decoded): ?>
            <table>
                <tr>
                    <th>RECIPIENT</th>
                    <td>
                        <?=$this->recipient?>
                        <span class="email">
                            <?= $this->recipientEmail ? "(".$this->recipientEmail.")":null?>
                        </span>
                    </td>
                </tr>                
                <tr>
                    <th>SENDER</th>
                    <td>
                        <?=$this->sender?>
                        <span class="email">
                            <?= $this->senderEmail ? "(".$this->senderEmail.")":null?>
                        </span>
                    </td>
                </tr>
                <tr>
                    <th>SEND ON</th>
                    <td><?=date("r",strtotime($this->date))?></td>                    
                </tr>
                <tr>
                    <th>DATA</th>
                    <td>
                        <textarea><?=$this->decoded?></textarea>
                    </td>                    
                </tr>
            </table>
            <? endif ?>
        </div>
    </body>
</html>    
