<?=$this->doctype() ?>
<html>
    <head>
        <?  $this->headScript()->appendFile('/js/jquery-1.9.1.min.js') ?>
        <?= $this->headScript()->appendFile('http://www.google.com/recaptcha/api/js/recaptcha_ajax.js') ?>
    </head>
    <style>
        body {
            margin:0; 
            padding:0; 
            text-align:center; 
            background:#eee; 
            box-shadow:inset 0 0 10em #aaa; 
            min-width:100%; 
            min-height:100%;
            position:absolute;
            font-family:Arial, Helvetica, sans-serif;
            }
            
        #dataForm {margin:3em 1em 1em; min-width:30em; display:inline-block; position:relative}
        #dataForm label {display:block; width:100%; text-align:left; padding:0 .5em; color:#888}
        #dataForm input, #dataForm textarea {
            width:98%; 
            padding:1%; 
            font-size:1.3em;
            border:1px solid #aaa;
            background:rgba(255,255,255,.6);
            box-shadow:inset 0 0 .1em #999;
            border-radius:.1em;
            margin-bottom:1em;
            }
        
        #dataForm textarea {min-height:10em; height:15em; min-width:30em}
        #dataForm .actions { overflow:hidden}
        #dataForm .actions button {float:right}
        #dataForm select {font-size:1.1em; width:100%; text-align:center}
        #dataForm button {
            background:#459; 
            border:none; 
            border-radius:.2em; 
            font-size:1.4em;
            padding:.3em 1em;
            color:#eee;
            margin:1em;
            box-shadow:0 0 .2em #222, inset 0 0 .7em #028;
            cursor:pointer;
            opacity:.9;
            }
            
        #dataForm button:hover {opacity:1}
        #recaptcha {margin-top:1em}
        #recaptcha_table {display:inline-block; border:none !important}
        .recaptcha_image_cell {background:none !important}
        
        #loader {
            position:absolute; 
            top:30%; 
            left:50%; 
            width:3em; 
            margin-left:-2em;
            padding:1em;
            background:#ccc;
            border-radius:.3em;
            opacity:.7;
            box-shadow:0 0 .2em #222;
            display:none;
            }
    </style>
    <body>
        <form id="dataForm" action="javascript:sendData()">
            <div>
                <label>NAME</label>
                <input class="name"/>
            </div>  
            <div>
                <label>DATA</label>
                <textarea class="data"></textarea>
            </div> 
            <div>
                <label>RECIPIENT</label>
                <select class="recipient">
                <? foreach ($this->recipients as $recipient): 
                    $name = $recipient->name ? $recipient->name." - " : null;
                ?>
                    <option value="<?=$recipient->id?>"><?= $name.$recipient->email ?></option>
                <? endforeach ?>
                </select>
            </div>
            <div id="recaptcha"></div>
            <div>    
                <button type="submit" disabled="true">SEND</button>
            </div> 
            <img id="loader" src="/images/loader.gif"/>
        </form>
    </body>
    <script>
        $(function(){
            Recaptcha.create("<?=RECAPTCHA_PUBLIC?>","recaptcha", {theme : "clean"});
            $('#dataForm button[type="submit"]').prop('disabled',false);
        });

    
        function sendData ()
        {
            var button = $('#dataForm button[type="submit"]');
            var params = {
                data      : $('#dataForm .data').val(),
                name      : $('#dataForm .name').val(),
                recipient : $('#dataForm .recipient').val(),
                challenge : Recaptcha.get_challenge(),
                response  : Recaptcha.get_response(),                   
            }
            
            if (!params['name']) {
                alert('You must enter your name.');
                return;
            } else if (!params['data']) {
                alert('data cannot be empty.');
                return;
            } else if (!params['response']) {
                alert('please type the words in the captcha image.');
                return;                
            }
            
            button.prop('disabled',true);
            $('#loader').fadeIn();
            $.ajax({
                url      : '/index/save',
                type     : 'post',
                dataType : 'json',
                data     : params,
                success  : function (data) {
                    $('#loader').fadeOut();
                    button.prop('disabled',false);
                    if (!data) {
                        alert('Unknwon Error');
                        return;
                    } else if (data['error'] == 'incorrect-captcha-sol') {
                        alert ('the captcha was incorrect. please try again.');
                    } else if (data['error']) alert (data['error']);    
                    if (data['message'])    alert(data['message']);
                    if (data['result']=='success') {
                        Recaptcha.destroy();
                        $('#dataForm')
                            .css({height:'100%',minHeight:'10em'})
                            .html('<img class="success" src="/images/success.png"><h1>Data succesfully sent!</h1>');
                    } else Recaptcha.reload();
                }
            }).error(function(){
                $('#loader').fadeOut();
                button.prop('disabled',false);
                Recaptcha.reload();
                alert('An unknown error occurred.');
            });
        }
    </script>
    
</html>